### ISSUE TITLE
Functions for example ping, traceroute, etc accept two argurments but you can't pass them

### ISSUE THREAD

**Issue by valduze** [telephone/LookingGlass#31]
Hello,
Functions like ping for example accept two arguments, how would you pass those to the web-interface. There is no extra text field to put those.

public function ping($host, $count = 4)

Please assist,
Regards,
Jongi

**Comment by s4m4n** [comment]
I didn't really understand what are you going to do. Would you clarify?

**Comment by afolson** [comment]
There are several arguments that `ping` accepts, and it'd be nice if there were a way to select a few of these or pass them through via the web interface instead of hard coding them in the source: https://github.com/telephone/LookingGlass/blob/master/LookingGlass/LookingGlass.php#L84-L87

The way it's set up now, the function accepts two arguments but the function falls back to the default count of `4` because there's no way to actually enter a count via the web interface.

**Comment by telephone** [comment]
> The way it's set up now, the function accepts two arguments but the function falls back to the default count of 4 because there's no way to actually enter a count via the web interface.

__The values are hard-coded for security__. Allowing user based values opens you up to abuse and shell escalation. If the values are not properly validated and escaped then a user can easily use your LG to hack into your server.

Version 1 was set-up with simplicity as the main goal, so everything was kept very basic. To allow user input, more validation and a lot of tests would be required. Even then, I wouldn't allow more than integers for user based input.

Let's use your example of 'count' being set via user interface. If you were to allow user input for 'count' in v1, you'd be susceptible to heavy abuse as there's no validation in v1. For example, a user could open multiple threads (under the rate-limit) and enter the count as '5,000,000'.
