### ISSUE TITLE
Feature request: Docker Container

### ISSUE THREAD

**Issue by SlothCroissant** [telephone/LookingGlass#42]
First off, I love the project - I've seen many great implementations of this across the web.

For my feature request, I'd love to see a Docker container that can be spun up that has all necessary prerequisites installed and set to go with Nginx, etc. It is a great way for users to check out LookingGlass quickly and easily, and would be ideal for folks like me who are running Docker in homelabs. The image could be hosted at https://hub.docker.com/.

**Comment by djh00t** [comment]
+1 we deploy all our code in docker containers, this would be very helpful.

**Comment by bbabich** [comment]
Would there be any interest to have this also utilising something like [Traefik](https://traefik.io/) at the frontend for https and what not?

I can spin something up...

**Comment by SlothCroissant** [comment]
That looks like it'd work great! I'm no help developing, but let me know if you need any testing done (I've got a Ubiquiti EdgeRouter ER-8 Pro I could test against), id love to beta this.

**Comment by walle89** [comment]
I don't think we should have Traefik or any other reverse proxy included in either Dockerfile or docker-compose files. That is something that needs to be separate. However we can have documentation about how to set up with Traefik, or otherwise how to get HTTPS with Let's Ecnrypt up and running.

For my projects I have planed to make it a docker container, the only problem is I have not found any time to look into it. If I ever getting around to it, then I can share my dockerfile and docker-compose files. And also I have waited to someone to accept one of PHP 7 pull requests (I try to avoid anything with PHP5).
